# Generated by Django 4.1.5 on 2023-12-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrecipe',
            old_name='description',
            new_name='food_description',
        ),
        migrations.RenameField(
            model_name='foodrecipe',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RemoveField(
            model_name='foodrecipe',
            name='image',
        ),
        migrations.AddField(
            model_name='foodrecipe',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_recipe_images'),
        ),
    ]
