# Generated by Django 4.1.5 on 2023-12-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_description_foodrecipe_food_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='food_image',
            field=models.ImageField(upload_to='food_recipe_images'),
        ),
    ]
